### ISSUE TITLE
Info.plist CFBundleVersion Issue in Xcode15.0.1

### ISSUE THREAD

**Issue by GaneshN-Petari** [whereby/ios-sdk#15]
There is an issue with CFBundleVersion while uploading the app to Appstore with latest Xcode.

Path: `WebRTC.xcframework/ios-arm64/WebRTC.framework/Info.plist`
Issue: `CFBundleVersion - b1.0.0`

> **Fix: `CFBundleVersion - b1.0.0` -> `CFBundleVersion - 1.0.0`**

**Comment by remi-quinto** [comment]
Hi [GaneshN-Petari](https://github.com/GaneshN-Petari), thanks for your feedback. We will look into it.

**Comment by remi-quinto** [comment]
Hi again @GaneshN-Petari, We have just released a new version of our ios SDK ([0.12.0](https://github.com/whereby/ios-sdk/releases/tag/0.12.0)) that should fix this issue. 
Feel free to try it out and let us know.

**Comment by remi-quinto** [comment]
Fixed
